import type { AutopilotScreen, TrustedSourceCategory, TrustedSourceConnectorType, TrustedSourceDataType, TrustedSourceTier } from '@/utils/trustedSources'

export interface TrustedSourceDiscoveryRoot {
  root_id: string
  tier_number: number
  title: string
  trust_tier: TrustedSourceTier
  category: TrustedSourceCategory
  data_types_supported: TrustedSourceDataType[]
  connector_type: TrustedSourceConnectorType
  allowed_for: AutopilotScreen[]
  confidence_default: 'low' | 'medium' | 'high'
  auto_update_allowed: boolean
  requires_review: boolean
  notes: string
  source_names: string[]
  source_count: number
}

const TRUSTED_SOURCE_DISCOVERY_ROOT_SEEDS: TrustedSourceDiscoveryRoot[] = [
  {
    "root_id": "registry-seed-01-official-trade-customs-macro-country-data",
    "tier_number": 1,
    "title": "Tier 1 - Official trade, customs, macro, country data",
    "trust_tier": "tier1-official",
    "category": "trade",
    "data_types_supported": [
      "trade_data",
      "market_size",
      "company_data"
    ],
    "connector_type": "API",
    "allowed_for": [
      "market",
      "exportMarkets",
      "executive"
    ],
    "confidence_default": "high",
    "auto_update_allowed": true,
    "requires_review": false,
    "notes": "Official trade, customs, macro, and country data roots. Prefer API or official portal evidence; product-specific assumptions still need review.",
    "source_names": [
      "UN Comtrade",
      "UN Comtrade Plus",
      "International Trade Centre",
      "ITC Trade Map",
      "World Bank Data",
      "World Bank API",
      "World Bank WITS",
      "World Bank DataBank",
      "WTO Data",
      "WTO Tariff Database",
      "IMF Data",
      "IMF Direction of Trade Statistics",
      "OECD Data",
      "OECD Data Explorer",
      "OECD STAN Database",
      "UNIDO Statistics",
      "UNCTADstat",
      "ILOSTAT",
      "FAOSTAT",
      "Eurostat",
      "Eurostat Database",
      "Eurostat Comext",
      "US Census International Trade",
      "USITC DataWeb",
      "FRED Economic Data",
      "U.S. BLS Producer Price Index",
      "U.S. BLS Import/Export Price Indexes",
      "U.S. EIA",
      "EU Access2Markets",
      "WTO Trade Profiles",
      "ASEANStats",
      "ADB Data Library",
      "Asian Development Bank Key Indicators",
      "African Development Bank Data Portal",
      "Islamic Development Bank Data",
      "China National Bureau of Statistics",
      "China General Administration of Customs",
      "China Ministry of Commerce",
      "China Ministry of Ecology and Environment",
      "China Ministry of Industry and Information Technology",
      "China Ministry of Emergency Management",
      "China State Administration for Market Regulation",
      "People’s Bank of China",
      "SAFE China",
      "China Customs Statistics",
      "Guangdong Government Data",
      "Guangzhou Government Data",
      "Nansha Free Trade Zone official sources",
      "Zhejiang Statistics Bureau",
      "Jiangsu Statistics Bureau",
      "Fujian Statistics Bureau",
      "Shandong Statistics Bureau",
      "Bangladesh Bank",
      "Bangladesh Export Promotion Bureau",
      "Bangladesh Bureau of Statistics",
      "Bangladesh National Board of Revenue",
      "Bangladesh Customs",
      "India Ministry of Commerce",
      "India DGFT",
      "India Ministry of Chemicals and Fertilizers",
      "India Department of Commerce Trade Statistics",
      "Vietnam General Statistics Office",
      "Vietnam Customs",
      "Turkey Statistical Institute",
      "Turkish Ministry of Trade",
      "Pakistan Bureau of Statistics",
      "Pakistan Customs",
      "Indonesia Statistics",
      "Indonesia Customs",
      "Malaysia Statistics Department",
      "Malaysia External Trade Development Corporation",
      "Thailand Customs",
      "Thailand Ministry of Commerce",
      "Egypt CAPMAS",
      "Brazil Ministry of Development, Industry, Trade and Services",
      "Brazil Comex Stat",
      "Mexico INEGI",
      "South Korea KOSIS",
      "Korea Customs Service",
      "Japan Statistics Bureau",
      "Japan Customs",
      "Singapore Department of Statistics",
      "Singapore Customs",
      "UAE Federal Competitiveness and Statistics Centre",
      "Saudi General Authority for Statistics",
      "South Africa Revenue Service trade statistics",
      "UK HMRC trade statistics",
      "UK ONS",
      "Canada Statistics Canada",
      "Canada Trade Data Online",
      "Australia ABS",
      "New Zealand Stats NZ",
      "Switzerland Federal Statistical Office",
      "Swiss Customs",
      "Hong Kong Census and Statistics Department",
      "Taiwan Directorate-General of Budget, Accounting and Statistics",
      "Taiwan Customs Administration",
      "Philippines Statistics Authority",
      "Philippines Customs",
      "Sri Lanka Customs"
    ],
    "source_count": 100
  },
  {
    "root_id": "registry-seed-02-chemical-price-commodity-market-reference-sources",
    "tier_number": 2,
    "title": "Tier 2 - Chemical price, commodity, market-reference sources",
    "trust_tier": "tier2-market-reference",
    "category": "price",
    "data_types_supported": [
      "price_data",
      "market_size"
    ],
    "connector_type": "paid_source",
    "allowed_for": [
      "market",
      "investment",
      "rawMaterials"
    ],
    "confidence_default": "medium",
    "auto_update_allowed": true,
    "requires_review": true,
    "notes": "Chemical price and market-reference roots. Prices remain review-gated unless tied to official indices or approved supplier evidence.",
    "source_names": [
      "SunSirs China Commodity Data",
      "SunSirs Chemical Spot Prices",
      "SunSirs Futures Price",
      "ECHEMI",
      "ECHEMI Weekly Price",
      "ECHEMI Price Database",
      "ECHEMI Market Insight",
      "ICIS",
      "ICIS Chemical Business",
      "Argus Media",
      "S&P Global Commodity Insights",
      "Platts petrochemical pricing",
      "ChemAnalyst",
      "ChemOrbis",
      "Polymerupdate",
      "Asian Metal",
      "Dalian Commodity Exchange",
      "Shanghai Futures Exchange",
      "Zhengzhou Commodity Exchange",
      "Bursa Malaysia Palm Oil Futures",
      "CME Group commodity data",
      "ICE Futures",
      "Investing.com commodities",
      "Trading Economics",
      "TradingView commodities",
      "OilChem China",
      "SCI99 China commodity data",
      "Baiinfo China commodity data",
      "Longzhong Information",
      "Mysteel commodity data",
      "100ppi / China Commodity Data",
      "Fastmarkets",
      "Metal Bulletin",
      "CRU Group",
      "Wood Mackenzie Chemicals",
      "NexantECA",
      "Tecnon OrbiChem",
      "Chemical Week",
      "Chemical Market Analytics",
      "OPIS",
      "RISI / Fastmarkets forest products",
      "Palm Oil Analytics",
      "MPOB Malaysia palm oil data",
      "GAPKI Indonesia palm oil data",
      "USDA commodity reports",
      "IndexMundi commodity prices",
      "Knoema commodity datasets",
      "Quandl / Nasdaq Data Link commodity datasets",
      "Macrotrends commodity data",
      "CEIC commodity indicators"
    ],
    "source_count": 50
  },
  {
    "root_id": "registry-seed-03-chemical-regulatory-sds-safety-compliance",
    "tier_number": 3,
    "title": "Tier 3 - Chemical regulatory, SDS, safety, compliance",
    "trust_tier": "tier2-market-reference",
    "category": "regulatory",
    "data_types_supported": [
      "regulatory_data",
      "document_evidence"
    ],
    "connector_type": "web_reference",
    "allowed_for": [
      "regulatory",
      "rawMaterials",
      "investorReadiness"
    ],
    "confidence_default": "medium",
    "auto_update_allowed": true,
    "requires_review": true,
    "notes": "Chemical regulatory, SDS, safety, and compliance roots. Official regulators outrank service providers and SDS mirrors.",
    "source_names": [
      "China MEE",
      "China IECSC resources",
      "CIRS Group",
      "ChemLinked",
      "Intertek Chemical Regulatory",
      "SGS Chemical Regulatory",
      "TÜV Rheinland Chemical Regulatory",
      "UL Prospector",
      "PubChem",
      "NCBI Chemical Database",
      "ECHA",
      "ECHA REACH Registered Substances",
      "ECHA Classification and Labelling Inventory",
      "US EPA CompTox",
      "US EPA TSCA Inventory",
      "NITE Japan CHRIP",
      "Japan Chemical Substance Control Law resources",
      "Korea Chemicals Management Association",
      "K-REACH resources",
      "Taiwan Chemical Substance Inventory resources",
      "Australia AICIS",
      "Canada DSL/NDSL",
      "New Zealand EPA Chemical Classification",
      "Singapore NEA Chemical Control",
      "Malaysia DOSH chemical safety",
      "India BIS",
      "India chemical management resources",
      "UNEP Chemicals and Waste",
      "OECD eChemPortal",
      "OECD QSAR Toolbox",
      "WHO IPCS",
      "ILO Chemical Safety Cards",
      "NIOSH Pocket Guide",
      "OSHA Chemical Database",
      "GESTIS Substance Database",
      "Sigma-Aldrich SDS",
      "Fisher Scientific SDS",
      "TCI Chemicals SDS",
      "Alfa Aesar SDS",
      "ChemicalBook SDS",
      "ChemSrc",
      "ChemBK",
      "ChemSpider",
      "CAS Common Chemistry",
      "PubChem Safety and Hazards",
      "European Chemicals Agency Guidance",
      "ZDHC Gateway",
      "ZDHC MRSL",
      "OEKO-TEX",
      "GOTS"
    ],
    "source_count": 50
  },
  {
    "root_id": "registry-seed-04-textile-apparel-dyeing-finishing-industry-sources",
    "tier_number": 4,
    "title": "Tier 4 - Textile, apparel, dyeing, finishing industry sources",
    "trust_tier": "tier2-market-reference",
    "category": "textile",
    "data_types_supported": [
      "market_size",
      "company_data"
    ],
    "connector_type": "web_reference",
    "allowed_for": [
      "market",
      "exportMarkets",
      "executive"
    ],
    "confidence_default": "medium",
    "auto_update_allowed": true,
    "requires_review": true,
    "notes": "Textile, apparel, dyeing, finishing, and industry-association roots for market context.",
    "source_names": [
      "ITMF",
      "Textile Exchange",
      "International Apparel Federation",
      "International Textile Manufacturers Federation reports",
      "China National Textile and Apparel Council",
      "China Textile Information Center",
      "China Dyeing and Printing Association",
      "China Chemical Fibers Association",
      "China Textile Magazine",
      "Textile World",
      "Fibre2Fashion",
      "Just Style",
      "Ecotextile News",
      "Textile Today",
      "Apparel Resources",
      "Sourcing Journal",
      "WTiN",
      "Knitting Industry",
      "The Textile Magazine India",
      "Indian Textile Journal",
      "Pakistan Textile Journal",
      "Vietnam Textile and Apparel Association",
      "Bangladesh Textile Mills Association",
      "Bangladesh Garment Manufacturers and Exporters Association",
      "Turkey Textile Employers Association",
      "Indonesian Textile Association",
      "Malaysian Textile Manufacturers Association",
      "Thailand Textile Institute",
      "Taiwan Textile Federation",
      "Korea Textile Development Institute",
      "Japan Textile Federation",
      "Hong Kong Research Institute of Textiles and Apparel",
      "AATCC",
      "Textile Institute UK",
      "Society of Dyers and Colourists",
      "Colour Index International",
      "Hohenstein",
      "Bluesign",
      "Sustainable Apparel Coalition",
      "Cascale",
      "Better Cotton",
      "Cotton Incorporated",
      "International Cotton Advisory Committee",
      "Textile ETP",
      "Fashion for Good",
      "Ellen MacArthur Foundation textiles reports",
      "McKinsey State of Fashion",
      "Deloitte chemical/manufacturing reports",
      "PwC chemicals reports",
      "KPMG chemical industry reports"
    ],
    "source_count": 50
  },
  {
    "root_id": "registry-seed-05-market-research-and-paid-reference-market-reports",
    "tier_number": 5,
    "title": "Tier 5 - Market research and paid/reference market reports",
    "trust_tier": "tier2-market-reference",
    "category": "market",
    "data_types_supported": [
      "market_size",
      "company_data"
    ],
    "connector_type": "paid_source",
    "allowed_for": [
      "market",
      "exportMarkets",
      "executive"
    ],
    "confidence_default": "medium",
    "auto_update_allowed": true,
    "requires_review": true,
    "notes": "Market research and paid/reference report roots. Never auto-approve market size, CAGR, or share without source scope and owner review.",
    "source_names": [
      "MarketsandMarkets",
      "Research and Markets",
      "Grand View Research",
      "Mordor Intelligence",
      "Fortune Business Insights",
      "IMARC Group",
      "Allied Market Research",
      "Data Bridge Market Research",
      "Transparency Market Research",
      "Global Market Insights",
      "Future Market Insights",
      "Fact.MR",
      "Technavio",
      "The Business Research Company",
      "QYResearch",
      "Frost & Sullivan",
      "Euromonitor",
      "Statista",
      "IBISWorld",
      "Freedonia Group",
      "BCC Research",
      "MarketWatch market reports",
      "PR Newswire market report releases",
      "GlobeNewswire market report releases",
      "Valuates Reports",
      "Verified Market Research",
      "Zion Market Research",
      "Polaris Market Research",
      "Coherent Market Insights",
      "SkyQuest Technology",
      "Precedence Research",
      "Towards Chemical and Materials reports",
      "ChemIntel360",
      "Ceresana",
      "Smithers",
      "IHS Markit legacy reports",
      "S&P Chemical Economics Handbook",
      "CMAI legacy chemical reports",
      "Nexant reports",
      "Tecnon OrbiChem reports",
      "Wood Mackenzie chemical reports",
      "ICIS Supply and Demand Database",
      "Argus chemical market reports",
      "Chemical Market Analytics reports",
      "BloombergNEF chemical/commodity data",
      "Fitch Solutions",
      "Moody’s industry reports",
      "S&P Ratings chemicals",
      "MSCI industry reports",
      "Refinitiv / LSEG industry data"
    ],
    "source_count": 50
  },
  {
    "root_id": "registry-seed-06-competitor-official-sources",
    "tier_number": 6,
    "title": "Tier 6 - Competitor official sources",
    "trust_tier": "tier2-market-reference",
    "category": "competitor",
    "data_types_supported": [
      "competitor_data",
      "company_data",
      "financial_data"
    ],
    "connector_type": "web_reference",
    "allowed_for": [
      "competitor",
      "market",
      "executive"
    ],
    "confidence_default": "medium",
    "auto_update_allowed": true,
    "requires_review": true,
    "notes": "Competitor official roots. Company pages can confirm products, catalogs, certifications, and public statements; metrics still need field-specific evidence.",
    "source_names": [
      "Evonik",
      "Stepan",
      "Kao Chemicals",
      "Wacker",
      "Rudolf Group",
      "CHT Group",
      "Archroma",
      "Zschimmer & Schwarz",
      "Pulcra Chemicals",
      "Transfar Chemicals",
      "BASF",
      "Dow",
      "Solvay / Syensqo",
      "Clariant",
      "Huntsman Textile Effects",
      "Lonsen",
      "Zhejiang Runtu",
      "Zhejiang Longsheng",
      "Dymatic Chemicals",
      "Nicca Chemical",
      "KISCO",
      "Bozzetto Group",
      "Tanatex Chemicals",
      "Sarex Chemicals",
      "Sarex Overseas",
      "Resil Chemicals",
      "Fineotex Chemical",
      "Rossari Biotech",
      "Atul Ltd",
      "Croda",
      "Nouryon",
      "AkzoNobel legacy chemicals",
      "Momentive",
      "Shin-Etsu",
      "Elkem Silicones",
      "Dow Silicones",
      "Wynca Group",
      "Hoshine Silicon",
      "Dongyue Group",
      "Bluestar Silicones",
      "KCC Silicone",
      "Elkem China",
      "DIC Corporation",
      "ADEKA",
      "Mitsubishi Chemical",
      "Toray",
      "Asahi Kasei",
      "LG Chem",
      "LOTTE Chemical",
      "SK Chemicals",
      "Reliance Industries",
      "Indian Oil Chemicals",
      "SABIC",
      "Sinopec",
      "PetroChina",
      "CNOOC Chemicals",
      "Hengli Petrochemical",
      "Rongsheng Petrochemical",
      "Wanhua Chemical",
      "Satellite Chemical",
      "Kingboard Chemical",
      "Zhejiang Huangma Technology",
      "Zhejiang Liansheng Chemical",
      "Jiangsu Dynamic Chemical",
      "Jiangsu Haian Petrochemical",
      "Jiangsu Xinya Chemical",
      "Shandong Jinling Chemical",
      "Shandong Haili Chemical",
      "Shandong Longlive Bio-Technology",
      "Guangdong Dymatic Fine Chemical",
      "Guangzhou DX Chemical",
      "Guangzhou Runhua Chemical",
      "Guangzhou Bafeorii Chemical",
      "Hubei Aging Chemical",
      "Hubei Greenhome Materials",
      "Jiangyin Huayuan Chemical",
      "Hangzhou Meigao Chemical",
      "Zhejiang Kefeng Silicone",
      "Zhejiang Xinan Chemical",
      "Guangzhou Tinci Materials",
      "Tianjin Dingshengxin Chemical",
      "Shanghai S&D Fine Chemical",
      "Shanghai Honneur Tech",
      "Foshan Ruisheng Chemical",
      "Dongguan City Betterly Chemical",
      "Qingdao Kerun Bioengineering",
      "Hunan Resun-Auway Industrial",
      "Hunan Lijie Biochemical",
      "Jiangsu WanQi Biotechnology",
      "Huntsman Corporation",
      "Nouryon Surfactants",
      "Sasol Chemicals",
      "Arkema",
      "INEOS",
      "KLK OLEO",
      "Wilmar Oleo",
      "Emery Oleochemicals",
      "IOI Oleochemical",
      "Vantage Specialty Chemicals",
      "Musim Mas Oleochemicals"
    ],
    "source_count": 100
  },
  {
    "root_id": "registry-seed-07-supplier-direct-quote-sources",
    "tier_number": 7,
    "title": "Tier 7 - Supplier/direct/quote sources",
    "trust_tier": "tier3-supplier-evidence",
    "category": "supplier",
    "data_types_supported": [
      "supplier_quote",
      "price_data",
      "document_evidence"
    ],
    "connector_type": "supplier_quote",
    "allowed_for": [
      "rawMaterials",
      "investment",
      "competitor"
    ],
    "confidence_default": "medium",
    "auto_update_allowed": true,
    "requires_review": true,
    "notes": "Supplier/direct/quote roots. These can support sourcing and scorecards after owner approval; confidential data remains RBAC-protected.",
    "source_names": [
      "Supplier proforma invoice",
      "Supplier formal quotation",
      "Supplier signed contract",
      "Supplier invoice",
      "Supplier COA",
      "Supplier TDS",
      "Supplier SDS",
      "Supplier ISO certificate",
      "Supplier business license",
      "Supplier export license",
      "Supplier factory audit report",
      "Supplier factory photos/videos",
      "Supplier WeChat quotation screenshot",
      "Supplier email quotation",
      "Supplier WhatsApp quotation",
      "Supplier sample delivery record",
      "Supplier batch test report",
      "Supplier shipment document",
      "Bill of lading",
      "Commercial invoice",
      "Packing list",
      "Insurance certificate",
      "Freight forwarder quote",
      "Customs declaration",
      "Import duty receipt",
      "Bank payment proof",
      "LC document",
      "TT payment receipt",
      "Third-party lab report",
      "SGS test report",
      "Intertek test report",
      "Bureau Veritas test report",
      "TÜV test report",
      "Customer trial report",
      "Customer feedback email",
      "Customer purchase order",
      "Customer complaint report",
      "Internal lab notebook",
      "Internal formulation sheet",
      "Internal cost sheet",
      "Factory production record",
      "QC pass/fail report",
      "Stability test report",
      "Shelf-life test report",
      "Application test report",
      "Competitor sample lab report",
      "Competitor product label",
      "Competitor SDS/TDS",
      "Competitor invoice",
      "Distributor quotation"
    ],
    "source_count": 50
  },
  {
    "root_id": "registry-seed-08-marketplaces-weak-reference-only",
    "tier_number": 8,
    "title": "Tier 8 - Marketplaces / weak reference only",
    "trust_tier": "tier4-public-listing",
    "category": "supplier",
    "data_types_supported": [
      "supplier_quote",
      "price_data"
    ],
    "connector_type": "web_reference",
    "allowed_for": [
      "market",
      "competitor",
      "rawMaterials"
    ],
    "confidence_default": "low",
    "auto_update_allowed": false,
    "requires_review": true,
    "notes": "Marketplaces and public listings are weak references only. Never mark Verified without direct supplier evidence.",
    "source_names": [
      "Alibaba",
      "Made-in-China",
      "1688",
      "Global Sources",
      "HKTDC Sourcing",
      "IndiaMART",
      "TradeIndia",
      "ExportHub",
      "EC21",
      "ECPlaza",
      "GlobalSpec",
      "Thomasnet",
      "Kompass",
      "Europages",
      "ChemNet",
      "LookChem",
      "GuideChem",
      "ChemicalBook supplier pages",
      "ChemBK supplier pages",
      "Molbase-style chemical marketplaces",
      "SpecialChem supplier pages",
      "UL Prospector supplier listings",
      "Knowde",
      "Covalo",
      "Prospector Chemical Marketplace",
      "ChemDirect",
      "BuyersGuideChem",
      "Chemical Register",
      "ChemIndustry.com",
      "RxChemicals marketplace"
    ],
    "source_count": 30
  },
  {
    "root_id": "registry-seed-09-logistics-freight-tariff-shipping",
    "tier_number": 9,
    "title": "Tier 9 - Logistics, freight, tariff, shipping",
    "trust_tier": "tier2-market-reference",
    "category": "trade",
    "data_types_supported": [
      "trade_data",
      "price_data"
    ],
    "connector_type": "web_reference",
    "allowed_for": [
      "exportMarkets",
      "investment",
      "rawMaterials"
    ],
    "confidence_default": "medium",
    "auto_update_allowed": true,
    "requires_review": true,
    "notes": "Logistics, freight, tariff, and shipping roots for landed-cost context. Route-specific cost claims require current source/date review.",
    "source_names": [
      "Freightos Baltic Index",
      "Drewry World Container Index",
      "Shanghai Shipping Exchange",
      "Baltic Exchange",
      "Xeneta",
      "Flexport market updates",
      "Maersk market updates",
      "MSC shipping schedules",
      "CMA CGM schedules",
      "COSCO Shipping",
      "Hapag-Lloyd",
      "ONE Line",
      "Evergreen Line",
      "Yang Ming",
      "OOCL",
      "PIL",
      "DHL Global Forwarding",
      "Kuehne+Nagel",
      "DSV",
      "DB Schenker",
      "Bangladesh Chittagong Port Authority",
      "China Port Association",
      "Guangzhou Port Group",
      "Ningbo-Zhoushan Port",
      "Shanghai Port",
      "Shenzhen Port",
      "Qingdao Port",
      "Tianjin Port",
      "Xiamen Port",
      "Nansha Port",
      "World Bank Logistics Performance Index",
      "WTO Tariff Download Facility",
      "WITS Tariff Data",
      "MacMap / Market Access Map",
      "EU Access2Markets tariffs",
      "UK Trade Tariff",
      "US HTS",
      "China Customs tariff database",
      "Bangladesh Customs tariff",
      "India Customs tariff"
    ],
    "source_count": 40
  },
  {
    "root_id": "registry-seed-10-currency-finance-investor-macro",
    "tier_number": 10,
    "title": "Tier 10 - Currency, finance, investor, macro",
    "trust_tier": "tier2-market-reference",
    "category": "finance",
    "data_types_supported": [
      "financial_data",
      "company_data"
    ],
    "connector_type": "web_reference",
    "allowed_for": [
      "investment",
      "investorReadiness",
      "presentation"
    ],
    "confidence_default": "medium",
    "auto_update_allowed": true,
    "requires_review": true,
    "notes": "Currency, finance, investor, macro, tax, and valuation roots. Investor claims remain review-gated.",
    "source_names": [
      "XE",
      "OANDA",
      "Wise mid-market rates",
      "ExchangeRate-API",
      "Open Exchange Rates",
      "European Central Bank exchange rates",
      "People’s Bank of China FX",
      "Bangladesh Bank exchange rates",
      "IMF exchange rate data",
      "FRED exchange rate data",
      "World Bank inflation indicators",
      "IMF WEO",
      "IMF IFS",
      "OECD inflation data",
      "Trading Economics macro data",
      "Damodaran data",
      "NYU Stern valuation datasets",
      "KPMG tax rates",
      "PwC tax summaries",
      "Deloitte tax guides",
      "EY tax guides",
      "China Briefing",
      "Dezan Shira China Briefing",
      "HKTDC Research",
      "InvestHK",
      "Invest Guangdong",
      "Invest Guangzhou",
      "Nansha Investment Promotion",
      "PwC China",
      "Deloitte China"
    ],
    "source_count": 30
  },
  {
    "root_id": "registry-seed-11-china-industrial-parks-location-investment",
    "tier_number": 11,
    "title": "Tier 11 - China industrial parks / location / investment",
    "trust_tier": "tier1-official",
    "category": "macro",
    "data_types_supported": [
      "company_data",
      "regulatory_data"
    ],
    "connector_type": "web_reference",
    "allowed_for": [
      "executive",
      "market",
      "investment",
      "regulatory"
    ],
    "confidence_default": "high",
    "auto_update_allowed": true,
    "requires_review": true,
    "notes": "China industrial park, location, and investment promotion roots. Use official pages but keep incentives/site assumptions reviewed.",
    "source_names": [
      "Guangdong Free Trade Zone official",
      "Nansha Free Trade Zone official",
      "Huangpu Development District official",
      "Guangzhou Development District official",
      "Shenzhen Qianhai official",
      "Zhuhai Hengqin official",
      "Zhejiang FTZ official",
      "Ningbo FTZ official",
      "Jiangsu industrial park official",
      "Suzhou Industrial Park official",
      "Changzhou chemical park sources",
      "Nantong chemical park sources",
      "Shanghai Chemical Industry Park",
      "Ningbo Petrochemical Economic and Technological Development Zone",
      "Daya Bay Petrochemical Industrial Zone",
      "Huizhou Daya Bay official",
      "Quanzhou Petrochemical Park",
      "Fujian Gulei Petrochemical Base",
      "Shandong Yantai Chemical Industrial Park",
      "Dongying Chemical Industrial Park",
      "Zibo Chemical Industrial Park",
      "Qingdao West Coast New Area",
      "Tianjin Nangang Industrial Zone",
      "Lianyungang Petrochemical Industry Base",
      "Nanjing Chemical Industry Park",
      "Hubei Yichang chemical park",
      "Hunan Yueyang petrochemical park",
      "Guangxi Qinzhou Port Area",
      "Beibu Gulf Port",
      "Hainan Free Trade Port"
    ],
    "source_count": 30
  },
  {
    "root_id": "registry-seed-12-certification-document-verification",
    "tier_number": 12,
    "title": "Tier 12 - Certification/document verification",
    "trust_tier": "tier2-market-reference",
    "category": "regulatory",
    "data_types_supported": [
      "document_evidence",
      "regulatory_data"
    ],
    "connector_type": "web_reference",
    "allowed_for": [
      "regulatory",
      "rawMaterials",
      "investorReadiness"
    ],
    "confidence_default": "medium",
    "auto_update_allowed": true,
    "requires_review": true,
    "notes": "Certification and document verification roots. Exact product/company matches need source URL/date.",
    "source_names": [
      "ZDHC Gateway product/company search",
      "OEKO-TEX Buying Guide",
      "GOTS Approved Chemical Inputs",
      "Bluesign Finder",
      "Higg / Cascale tools",
      "GRS certification database",
      "RCS certification database",
      "ISO certificate issuer verification",
      "SGS certificate verification",
      "Intertek certificate verification",
      "Bureau Veritas verification",
      "TÜV certificate verification",
      "UL certificate verification",
      "DNV certificate verification",
      "Lloyd’s Register verification",
      "China CNCA certification sources",
      "China CQC",
      "Bangladesh BSTI",
      "India BIS certification",
      "Hohenstein certificate verification"
    ],
    "source_count": 20
  },
  {
    "root_id": "registry-seed-13-academic-patents-technical",
    "tier_number": 13,
    "title": "Tier 13 - Academic / patents / technical",
    "trust_tier": "tier2-market-reference",
    "category": "chemical",
    "data_types_supported": [
      "document_evidence",
      "regulatory_data"
    ],
    "connector_type": "web_reference",
    "allowed_for": [
      "regulatory",
      "rawMaterials",
      "market"
    ],
    "confidence_default": "medium",
    "auto_update_allowed": true,
    "requires_review": true,
    "notes": "Academic, patent, and technical roots. Useful for technology context, not business truth without review.",
    "source_names": [
      "Google Scholar",
      "Crossref",
      "ResearchGate",
      "ScienceDirect",
      "SpringerLink",
      "Wiley Online Library",
      "Taylor & Francis",
      "ACS Publications",
      "RSC Publishing",
      "MDPI",
      "Frontiers",
      "Elsevier Engineering Village",
      "Scopus",
      "Web of Science",
      "PubMed",
      "Semantic Scholar",
      "BASE academic search",
      "CORE",
      "Lens.org patents/scholar",
      "Google Patents",
      "WIPO Patentscope",
      "Espacenet",
      "USPTO Patent Center",
      "China CNIPA patent search",
      "Japan J-PlatPat",
      "Korea KIPRIS",
      "India Patent Office",
      "Derwent Innovation",
      "FreePatentsOnline",
      "PatentScope chemical patents"
    ],
    "source_count": 30
  },
  {
    "root_id": "registry-seed-14-industry-media-news-lower-trust-than-primary-sources",
    "tier_number": 14,
    "title": "Tier 14 - Industry media / news, lower trust than primary sources",
    "trust_tier": "tier2-market-reference",
    "category": "market",
    "data_types_supported": [
      "market_size",
      "competitor_data"
    ],
    "connector_type": "web_reference",
    "allowed_for": [
      "market",
      "competitor"
    ],
    "confidence_default": "medium",
    "auto_update_allowed": false,
    "requires_review": true,
    "notes": "Industry media/news roots. Lower trust than primary sources; stage as review items.",
    "source_names": [
      "Chemical & Engineering News",
      "Chemical Week",
      "ICIS News",
      "Argus Chemical News",
      "S&P Commodity Insights News",
      "ChemEurope",
      "World Chemical Distributor Directory",
      "SpecialChem News",
      "Cosmetics & Toiletries, for surfactants adjacent",
      "Coatings World, for silicone/surfactant adjacent",
      "Adhesives & Sealants Industry",
      "Nonwovens Industry",
      "Textile World News",
      "Textile Today News",
      "Fibre2Fashion News",
      "Just Style News",
      "Ecotextile News",
      "Apparel Insider",
      "Sourcing Journal News",
      "Fashion Network"
    ],
    "source_count": 20
  },
  {
    "root_id": "registry-seed-15-competitor-filings-financial-data",
    "tier_number": 15,
    "title": "Tier 15 - Competitor filings / financial data",
    "trust_tier": "tier1-official",
    "category": "finance",
    "data_types_supported": [
      "financial_data",
      "company_data"
    ],
    "connector_type": "API",
    "allowed_for": [
      "competitor",
      "investment",
      "investorReadiness"
    ],
    "confidence_default": "high",
    "auto_update_allowed": true,
    "requires_review": true,
    "notes": "Competitor filings and financial-data roots. Use for company-wide context only unless product-line scope is explicit.",
    "source_names": [
      "Company annual reports",
      "Stock exchange filings",
      "Hong Kong Exchange filings",
      "Shanghai Stock Exchange filings",
      "Shenzhen Stock Exchange filings",
      "National Stock Exchange India filings",
      "Bombay Stock Exchange filings",
      "Tokyo Stock Exchange filings",
      "Korea Exchange filings",
      "Singapore Exchange filings",
      "SEC EDGAR",
      "Companies House UK",
      "EU business registers",
      "OpenCorporates",
      "Crunchbase, reference only",
      "PitchBook, paid source",
      "CB Insights, paid source",
      "D&B Hoovers, paid source",
      "Orbis / Bureau van Dijk",
      "S&P Capital IQ"
    ],
    "source_count": 20
  },
  {
    "root_id": "registry-seed-16-more-chemical-company-official-sources",
    "tier_number": 16,
    "title": "Tier 16 - More chemical company official sources",
    "trust_tier": "tier2-market-reference",
    "category": "competitor",
    "data_types_supported": [
      "competitor_data",
      "company_data"
    ],
    "connector_type": "web_reference",
    "allowed_for": [
      "competitor",
      "market",
      "executive"
    ],
    "confidence_default": "medium",
    "auto_update_allowed": true,
    "requires_review": true,
    "notes": "Additional chemical company official roots for competitor and supplier discovery.",
    "source_names": [
      "Lubrizol",
      "Ashland",
      "Innospec",
      "Elementis",
      "Nouryon",
      "Solenis",
      "Kemira",
      "LANXESS",
      "Covestro",
      "Perstorp",
      "Eastman",
      "Celanese",
      "LyondellBasell",
      "OQ Chemicals",
      "Oxea",
      "Shell Chemicals",
      "ExxonMobil Chemical",
      "TotalEnergies Chemicals",
      "Formosa Plastics",
      "LG Chem",
      "Lotte Chemical",
      "Hanwha Solutions",
      "SK Geo Centric",
      "Thai Oleochemicals",
      "KLK OLEO China",
      "Wilmar China",
      "P&G Chemicals",
      "IOI Pan-Century Oleochemicals",
      "Kao Chemicals Europe",
      "Stepan Asia"
    ],
    "source_count": 30
  },
  {
    "root_id": "registry-seed-17-more-raw-material-specific-sources",
    "tier_number": 17,
    "title": "Tier 17 - More raw-material specific sources",
    "trust_tier": "tier2-market-reference",
    "category": "chemical",
    "data_types_supported": [
      "price_data",
      "supplier_quote",
      "document_evidence"
    ],
    "connector_type": "web_reference",
    "allowed_for": [
      "rawMaterials",
      "investment",
      "competitor"
    ],
    "confidence_default": "medium",
    "auto_update_allowed": true,
    "requires_review": true,
    "notes": "Raw-material specific roots for stearic acid, TEA, DMS, silicone oil, acids, and related inputs.",
    "source_names": [
      "Palm Oil Analytics",
      "MPOC",
      "Malaysian Palm Oil Council",
      "Indonesian Palm Oil Association",
      "RSPO",
      "Oleochemical market reports from ICIS",
      "Oleochemical market reports from ChemAnalyst",
      "Fatty acid supplier catalogs",
      "Stearic acid supplier catalogs",
      "TEA supplier catalogs",
      "Dimethyl sulfate SDS/supplier pages",
      "Epichlorohydrin price pages",
      "Ethylene oxide price pages",
      "Acrylic acid price pages",
      "Butyl acrylate price pages",
      "Acetic acid price pages",
      "Formic acid price pages",
      "Silicone oil supplier pages",
      "Amino silicone fluid supplier pages",
      "Precipitated silica supplier pages"
    ],
    "source_count": 20
  },
  {
    "root_id": "registry-seed-18-dashboard-specific-internal-sources",
    "tier_number": 18,
    "title": "Tier 18 - Dashboard-specific internal sources",
    "trust_tier": "tier3-supplier-evidence",
    "category": "internal",
    "data_types_supported": [
      "internal_activity",
      "document_evidence",
      "financial_data"
    ],
    "connector_type": "manual_upload",
    "allowed_for": [
      "executive",
      "investment",
      "market",
      "competitor",
      "rawMaterials",
      "exportMarkets",
      "regulatory",
      "investorReadiness",
      "presentation"
    ],
    "confidence_default": "medium",
    "auto_update_allowed": true,
    "requires_review": true,
    "notes": "Dashboard-specific internal Hermes/Chemicon roots. Sensitive files, formulas, cost sheets, and investor notes remain RBAC-gated.",
    "source_names": [
      "Hermes Chat Sessions",
      "Hermes Session Capture summaries",
      "Hermes Memory",
      "Hermes Kanban Tasks",
      "Hermes Jobs",
      "Hermes Files/Documents",
      "Hermes Research Result Review",
      "Hermes Investor Readiness data",
      "Hermes IRR Calculator scenarios",
      "Hermes Market Intelligence local state",
      "Hermes Competitor Intelligence local state",
      "Hermes Raw Material Sourcing local state",
      "Hermes Export Market Opportunity local state",
      "Hermes Last 24 Hours",
      "Hermes Trusted Sources registry",
      "Hermes Local Backup Vault exports",
      "Chemicon uploaded brochure",
      "Chemicon product TDS files",
      "Chemicon SDS/MSDS files",
      "Chemicon COA files",
      "Chemicon formulation sheets",
      "Chemicon cost sheets",
      "Chemicon investor notes",
      "Chemicon supplier quotes",
      "Chemicon machine quotes",
      "Chemicon factory documents",
      "Chemicon regulatory consultant reports",
      "Chemicon customer trial feedback",
      "Chemicon competitor sample reports",
      "Chemicon financial model files"
    ],
    "source_count": 30
  }
]

export const TRUSTED_SOURCE_DISCOVERY_ROOTS: TrustedSourceDiscoveryRoot[] = TRUSTED_SOURCE_DISCOVERY_ROOT_SEEDS.map(root => ({
  ...root,
  source_names: [...root.source_names],
}))

export const TRUSTED_SOURCE_DISCOVERY_ROOT_COUNT = TRUSTED_SOURCE_DISCOVERY_ROOTS.reduce((total, root) => total + root.source_count, 0)

export function trustedSourceDiscoveryRootSummaryLines(): string[] {
  return TRUSTED_SOURCE_DISCOVERY_ROOTS.map(root =>
    `${root.title}: ${root.source_count} roots; trust=${root.trust_tier}; connector=${root.connector_type}; review=${root.requires_review ? 'yes' : 'no'}`,
  )
}

export function trustedSourceDiscoveryRootPromptLines(maxNamesPerRoot = 18): string[] {
  return TRUSTED_SOURCE_DISCOVERY_ROOTS.map(root => {
    const shown = root.source_names.slice(0, maxNamesPerRoot).join(', ')
    const remaining = root.source_count > maxNamesPerRoot ? `; plus ${root.source_count - maxNamesPerRoot} more` : ''
    return `${root.title}: ${shown}${remaining}. Policy: ${root.notes}`
  })
}

export function trustedSourceDiscoveryRootExamples(root: TrustedSourceDiscoveryRoot, count = 12): string[] {
  return root.source_names.slice(0, count)
}
